//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeatGrinder.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int ID { get; set; }
        public int GoalID { get; set; }
        public string Description { get; set; }
        public Nullable<int> ParentTaskID { get; set; }
        public int UserID { get; set; }
        public bool IsComplete { get; set; }
    }
}
